import React, { useState } from 'react';
import { Link, useParams } from 'react-router-dom';

const ReportGeneration: React.FC = () => {
  const { id } = useParams();
  const [isGenerating, setIsGenerating] = useState(false);
  const [completed, setCompleted] = useState(false);
  const [progress, setProgress] = useState(0);

  const startGeneration = () => {
    setIsGenerating(true);
    let curr = 0;
    const interval = setInterval(() => {
      curr += 1;
      setProgress(curr);
      if (curr >= 8) {
        clearInterval(interval);
        setTimeout(() => {
          setIsGenerating(false);
          setCompleted(true);
        }, 500);
      }
    }, 800);
  };

  const downloadReport = () => {
    const content = `FINFLOW FORENSIC REPORT\n\nCase: ${id || 'CC/2026/0042'}\nOfficer: Insp. Ravi Shankar K\nStatus: SIGNED & VERIFIED\n\n(This is a mock report file generated by the FinFlow UI demonstration.)`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `FinFlow_Report_${id || 'CC_2026_0042'}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const steps = [
    'Compiling transaction register…',
    'Rendering fund-flow network diagram…',
    'Computing final flag confidence scores…',
    'Generating Section 65B certificate…',
    'Applying RFC 3161 timestamp…',
    'Signing PDF with case officer credentials…',
    'Verifying signature integrity…',
    'Writing to output…'
  ];

  return (
    <div className="min-h-screen bg-void flex flex-col p-8 text-text-primary">
      {/* Header */}
      <div className="mb-10">
        <h1 className="font-serif text-[2.25rem] text-text-primary leading-none mb-3">GENERATE COURT-ADMISSIBLE REPORT</h1>
        <p className="font-sans text-[0.875rem] text-text-muted">Section 65B compliant · RFC 3161 timestamp · Tamper-evident chain of custody</p>
      </div>

      <div className="flex gap-12 max-w-[1200px] w-full">
        {/* Left Column (Form) */}
        <div className="w-[450px] flex flex-col shrink-0">
          
          <div className="bg-surface border border-border p-5 mb-6">
            <div className="font-mono text-[0.8rem] space-y-2 text-text-muted">
              <div className="flex"><span className="w-32">CASE:</span><span className="text-text-primary">{id || 'CC/2026/0042'}</span></div>
              <div className="flex"><span className="w-32">OFFICER:</span><span className="text-text-primary">Insp. Ravi Shankar K · CB-CID</span></div>
              <div className="flex"><span className="w-32">PERIOD:</span><span className="text-text-primary">01 Jan 2026 – 14 Jun 2026</span></div>
              <div className="flex"><span className="w-32">FILES:</span><span className="text-text-primary">8 source files</span></div>
              <div className="flex"><span className="w-32">TRANSACTIONS:</span><span className="text-text-primary">38,421 analyzed</span></div>
              <div className="flex"><span className="w-32">FLAGS:</span><span className="text-text-primary">247 total <span className="text-text-muted">(42 HIGH · 89 MEDIUM · 116 LOW)</span></span></div>
            </div>
          </div>

          <div className="mb-6 space-y-3 font-sans text-[0.85rem] text-text-primary">
            <label className="flex items-center gap-3 cursor-pointer">
              <input type="checkbox" defaultChecked className="w-4 h-4 accent-amber border-border rounded-[2px]" />
              <span>Section 1 — Case Metadata & Source File Inventory</span>
            </label>
            <label className="flex items-center gap-3 cursor-pointer">
              <input type="checkbox" defaultChecked className="w-4 h-4 accent-amber border-border rounded-[2px]" />
              <span>Section 2 — Executive Summary</span>
            </label>
            <label className="flex items-center gap-3 cursor-pointer">
              <input type="checkbox" defaultChecked className="w-4 h-4 accent-amber border-border rounded-[2px]" />
              <span>Section 3 — Fund-Flow Network (SVG diagram)</span>
            </label>
            <label className="flex items-center gap-3 cursor-pointer">
              <input type="checkbox" defaultChecked className="w-4 h-4 accent-amber border-border rounded-[2px]" />
              <span>Section 4 — Alert Detail (High triage only by default)</span>
            </label>
            <div className="ml-7 flex gap-4 text-[0.8rem] text-text-muted">
              <span className="flex items-center gap-1">└─ Also include:</span>
              <label className="flex items-center gap-2 cursor-pointer"><input type="radio" name="alerts" /> Medium</label>
              <label className="flex items-center gap-2 cursor-pointer"><input type="radio" name="alerts" /> All</label>
            </div>
            <label className="flex items-center gap-3 cursor-pointer">
              <input type="checkbox" defaultChecked className="w-4 h-4 accent-amber border-border rounded-[2px]" />
              <span>Section 5 — Complete Transaction Register</span>
            </label>
            <label className="flex items-center gap-3 cursor-pointer">
              <input type="checkbox" defaultChecked className="w-4 h-4 accent-amber border-border rounded-[2px]" />
              <span>Annexure A — Section 65B Certificate</span>
            </label>
            <label className="flex items-center gap-3 cursor-pointer">
              <input type="checkbox" defaultChecked className="w-4 h-4 accent-amber border-border rounded-[2px]" />
              <span>Annexure B — Chain of Custody Log</span>
            </label>
          </div>

          <div className="mb-6">
            <h3 className="t-subhead text-text-muted mb-3">DIGITAL SIGNATURE</h3>
            <div className="w-full h-px bg-border-dim mb-3" />
            <div className="font-sans text-[0.8rem] text-text-primary space-y-3">
              <div>
                <div className="mb-1">RFC 3161 Timestamp Authority</div>
                <div className="flex justify-between items-center text-[0.75rem]">
                  <span className="text-text-muted flex items-center gap-2">Status: <span className="text-risk-clean font-bold">● ONLINE</span> (local bundled TSA active)</span>
                </div>
                <div className="mt-2 flex bg-input p-0.5 rounded-[3px] w-fit border border-border">
                  <button className="px-3 py-1 bg-elevated border border-border-dim text-text-primary text-[0.7rem] font-bold rounded-[2px]">ONLINE</button>
                  <button className="px-3 py-1 text-text-muted text-[0.7rem] font-bold">OFFLINE / AIR-GAPPED</button>
                </div>
              </div>
              <div className="mt-4 pt-3 border-t border-border-dim">
                <div className="flex items-center gap-2 mb-1">
                  SHA-256 Signing: <span className="text-risk-clean font-bold">● ENABLED</span>
                </div>
                <p className="text-[0.75rem] text-text-muted">Signature embeds: hash + timestamp token in PDF metadata</p>
              </div>
            </div>
          </div>

          <div className="mb-8 bg-surface border border-border p-4">
            <h3 className="t-subhead text-text-muted mb-3">STATUTORY COMPLIANCE CHECK</h3>
            <div className="w-full h-px bg-border-dim mb-3" />
            <div className="font-mono text-[0.75rem] space-y-2">
              <div className="flex items-center gap-3"><span className="text-risk-clean font-bold">✓</span> <span className="text-text-muted w-40">Indian Evidence Act § 65B</span> <span className="text-text-primary flex-1">— certificate auto-generated</span></div>
              <div className="flex items-center gap-3"><span className="text-risk-clean font-bold">✓</span> <span className="text-text-muted w-40">PMLA § 12</span> <span className="text-text-primary flex-1">— STR/CTR fields validated</span></div>
              <div className="flex items-center gap-3"><span className="text-risk-clean font-bold">✓</span> <span className="text-text-muted w-40">IT Act § 79A</span> <span className="text-text-primary flex-1">— audit trail structured</span></div>
              <div className="flex items-center gap-3"><span className="text-risk-clean font-bold">✓</span> <span className="text-text-muted w-40">FATF Recommendation 16</span> <span className="text-text-primary flex-1">— wire transfer documentation</span></div>
            </div>
          </div>

          {!completed && (
            <button 
              onClick={startGeneration}
              disabled={isGenerating}
              className={`w-full font-sans font-bold text-[0.9rem] uppercase tracking-[0.08em] py-3 h-12 rounded-[3px] transition-all focus:outline-none 
                ${isGenerating ? 'bg-amber-dim text-void cursor-not-allowed' : 'bg-amber text-white hover:brightness-110'}`}
            >
              GENERATE SIGNED REPORT
            </button>
          )}

        </div>

        {/* Right Column (Preview) */}
        <div className="flex-1 relative flex items-center justify-center bg-surface border border-border overflow-hidden">
          
          <div className={`w-[400px] h-[550px] bg-white shadow-2xl transition-opacity duration-500 flex flex-col p-8 ${isGenerating || completed ? 'opacity-20 blur-sm' : 'opacity-100'}`}>
            {/* Illustrative PDF Preview */}
            <div className="w-full h-4 bg-gray-200 mb-8" />
            <div className="w-3/4 h-6 bg-gray-300 mb-6 font-serif text-black opacity-30">FINFLOW FORENSIC REPORT</div>
            <div className="w-full h-px bg-gray-300 mb-6" />
            <div className="space-y-3 flex-1">
              {Array.from({length: 12}).map((_, i) => (
                <div key={i} className={`h-2 bg-gray-200 ${i % 3 === 0 ? 'w-3/4' : 'w-full'}`} />
              ))}
              <div className="w-full h-32 bg-gray-100 border border-gray-200 my-6 flex items-center justify-center">
                 <div className="w-16 h-16 rounded-full border-4 border-gray-200" />
              </div>
              {Array.from({length: 6}).map((_, i) => (
                <div key={i} className={`h-2 bg-gray-200 ${i % 2 === 0 ? 'w-5/6' : 'w-full'}`} />
              ))}
            </div>
            <div className="mt-auto pt-4 border-t border-gray-200 flex justify-center">
              <span className="font-mono text-[0.65rem] text-gray-400">Estimated: 48 pages</span>
            </div>
          </div>

          {/* Progress Overlay */}
          {isGenerating && (
            <div className="absolute inset-0 flex flex-col items-center justify-center bg-void/80 backdrop-blur-md z-10 p-10">
              <div className="w-full max-w-[400px] flex flex-col space-y-3 font-mono text-[0.8rem]">
                {steps.map((step, i) => {
                  const isDone = i < progress;
                  const isActive = i === progress;
                  const isPending = i > progress;
                  
                  return (
                    <div key={i} className={`flex items-center gap-4 transition-colors duration-300 ${isDone ? 'text-text-muted' : isActive ? 'text-amber' : 'text-text-muted/30'}`}>
                      {isDone ? (
                        <div className="w-2 h-2 rounded-full bg-risk-clean shrink-0" />
                      ) : isActive ? (
                        <div className="w-2 h-2 rounded-full bg-amber animate-pulse shrink-0" />
                      ) : (
                        <div className="w-2 h-2 rounded-full border border-text-muted/30 shrink-0" />
                      )}
                      <span>{step}</span>
                    </div>
                  );
                })}
              </div>
              <div className="absolute bottom-0 left-0 right-0 h-1 bg-surface">
                <div className="h-full bg-amber transition-all duration-300 ease-linear" style={{ width: `${(progress / 8) * 100}%` }} />
              </div>
            </div>
          )}

          {/* Completed State */}
          {completed && (
            <div className="absolute inset-0 flex flex-col items-center justify-center bg-void/90 backdrop-blur-sm z-20 p-10">
              <div className="flex items-center gap-3 mb-8">
                <span className="text-risk-clean text-[2rem]">✓</span>
                <h2 className="font-sans font-bold text-[1.25rem] text-text-primary tracking-wide">REPORT GENERATED AND SIGNED</h2>
              </div>
              
              <button 
                onClick={downloadReport}
                className="w-full max-w-[320px] bg-amber text-white font-sans font-bold text-[0.9rem] uppercase tracking-[0.06em] py-4 rounded-[3px] mb-8 hover:brightness-110 shadow-[0_0_15px_rgba(212,134,10,0.2)] focus:outline-none"
              >
                ▼ DOWNLOAD REPORT — 48 pages, 4.2 MB
              </button>
              
              <div className="bg-surface border border-border p-6 w-full max-w-[400px]">
                <p className="font-sans text-[0.8rem] text-text-muted mb-1">SHA-256 of report:</p>
                <div className="flex items-center gap-2 mb-6">
                  <span className="font-mono text-[0.8rem] text-text-primary">8f3a1d9c2e4b8f3a1d9c2e4b8f3a1d9c</span>
                  <button className="text-amber text-[0.75rem] font-sans hover:underline focus:outline-none">[copy]</button>
                </div>
                
                <div className="space-y-1 font-mono text-[0.75rem]">
                  <div className="flex justify-between"><span className="text-text-muted">Signed at:</span><span className="text-text-primary">09:51:04 UTC+5:30</span></div>
                  <div className="flex justify-between"><span className="text-text-muted">RFC 3161 token embedded:</span><span className="text-risk-clean font-bold">YES</span></div>
                  <div className="flex justify-between"><span className="text-text-muted">Signature status:</span><span className="text-risk-clean font-bold">VALID</span></div>
                </div>
              </div>
              
              <Link to={`/case/${id || 'CC-2026-0042'}`} className="mt-8 text-text-muted hover:text-text-primary font-sans text-[0.85rem] inline-block">
                ← Back to case workspace
              </Link>
            </div>
          )}
          
        </div>
      </div>
    </div>
  );
};

export default ReportGeneration;
